# Generated by Django 4.2.1 on 2023-06-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolioDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='show',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
